spring:
  application:
    name : statistics-service

  profiles:
    active: ${PROFILE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

stream:
  key:
    member-joined: ${MEMBER_JOINED_KEY}
  group:
    member-joined: ${MEMBER_JOINED_GROUP}
  consumer:
    member-joined: ${MEMBER_JOINED_CONSUMER}

security:
  cors:
    paths:
      - ${APP_FRONT}
      - ${CREATOR_FRONT}
      - ${ADMIN_FRONT}