server:
  port: 9005

spring:
  application:
    name : statistics-service

  profiles:
    active: ${PROFILE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}